[package]
name = "lysi"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.60", features = ["derive"] }
kamadak-exif = "0.6.1"
md5 = "0.8.0"
walkdir = "2.5.0"
twox-hash = "2.1.2"
